// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyScheduler.API.Core.Persistence;

#nullable disable

namespace StudyScheduler.API.Core.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805120000_NotificationsRedesign")]
    partial class NotificationsRedesign
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyScheduler.Domain.Lessons.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCustomized")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("OccurrenceDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Topic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("TutorTelegramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "OccurrenceDate")
                        .IsUnique()
                        .HasFilter("\"SeriesId\" IS NOT NULL");

                    b.HasIndex("TutorTelegramId", "StartUtc");

                    b.ToTable("Lessons", null, t =>
                        {
                            t.HasCheckConstraint("CK_Lessons_SeriesSlotPair", "(\"SeriesId\" IS NULL) = (\"OccurrenceDate\" IS NULL)");

                            t.HasCheckConstraint("CK_Lessons_TutorTelegramIdPositive", "\"TutorTelegramId\" > 0");
                        });
                });

            modelBuilder.Entity("StudyScheduler.Domain.Lessons.LessonSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("TutorTelegramId")
                        .HasColumnType("bigint");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Pattern", "StudyScheduler.Domain.Lessons.LessonSeries.Pattern#WeeklyPattern", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Days")
                                .HasColumnType("integer")
                                .HasColumnName("Weekdays");

                            b1.Property<int>("DurationMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("DurationMinutes");

                            b1.Property<TimeOnly>("StartTimeLocal")
                                .HasColumnType("time without time zone")
                                .HasColumnName("StartTimeLocal");

                            b1.Property<string>("TimeZone")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("TimeZoneId");
                        });

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TutorTelegramId");

                    b.ToTable("LessonSeries", null, t =>
                        {
                            t.HasCheckConstraint("CK_LessonSeries_TutorTelegramIdPositive", "\"TutorTelegramId\" > 0");
                        });
                });

            modelBuilder.Entity("StudyScheduler.Domain.Notifications.NotificationDispatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("LocalDate")
                        .HasColumnType("date");

                    b.Property<int?>("MessageId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("RenderedSnapshot");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("TutorTelegramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChatId", "MessageId");

                    b.HasIndex("State", "ExpiresAtUtc");

                    b.HasIndex("TutorTelegramId", "Kind", "LessonId")
                        .IsUnique()
                        .HasFilter("\"State\" = 'Delivered' AND \"LessonId\" IS NOT NULL");

                    b.HasIndex("TutorTelegramId", "Kind", "LocalDate")
                        .IsUnique()
                        .HasFilter("\"State\" = 'Delivered' AND \"LocalDate\" IS NOT NULL");

                    b.ToTable("NotificationDispatches", null, t =>
                        {
                            t.HasCheckConstraint("CK_NotificationDispatches_Target", "((\"Kind\" = 'Reminder') = (\"LessonId\" IS NOT NULL)) AND ((\"Kind\" <> 'Reminder') = (\"LocalDate\" IS NOT NULL))");

                            t.HasCheckConstraint("CK_NotificationDispatches_TutorTelegramIdPositive", "\"TutorTelegramId\" > 0");
                        });
                });

            modelBuilder.Entity("StudyScheduler.Domain.Students.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("TutorTelegramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TutorTelegramId");

                    b.ToTable("Students", null, t =>
                        {
                            t.HasCheckConstraint("CK_Students_TutorTelegramIdPositive", "\"TutorTelegramId\" > 0");
                        });
                });

            modelBuilder.Entity("StudyScheduler.Domain.Tutors.TutorProfile", b =>
                {
                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("BotReachable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DaySummary")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<bool>("MorningAgenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<TimeOnly>("MorningAgendaAtLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time without time zone")
                        .HasDefaultValue(new TimeOnly(8, 0, 0));

                    b.Property<int?>("RemindMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TimeZoneId");

                    b.HasKey("TelegramUserId");

                    b.ToTable("TutorProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_TutorProfiles_TelegramUserIdPositive", "\"TelegramUserId\" > 0");
                        });
                });

            modelBuilder.Entity("StudyScheduler.Domain.Lessons.Lesson", b =>
                {
                    b.HasOne("StudyScheduler.Domain.Lessons.LessonSeries", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
